### ISSUE TITLE
Random room generation

### ISSUE THREAD

**Issue by wflms20110333** [16lawrencel/6073-game3#17]

**Comment by 16lawrencel** [comment]
Potential ideas:
1. New scene for each room, transition between scenes when moving between rooms (doesn't seem possible in Unity)
2. Keep track of game objects in room, when you move to a new room, disable the current game objects, then create new objects for the new room and enable them.
3. Create a bunch of rooms (in actual geographical layout), then just move camera when moving between rooms.
* And disable objects in other rooms
* But has advantage that we can create new room types, maybe large rooms.
